title: "David Matias"
url: "https://davidmatiasg.github.io"
description: "PhD Student in Economics at Rice University | Energy Markets, Industrial Organization & Regulatory Economics"
markdown: kramdown
permalink: pretty

collections:
  energy_posts:
    output: true
    permalink: /energy-markets/:name/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
